version: '3'

services:
  awsuper-server:
    container_name: awsuper
    image: node:10.4.0-stretch
    ports: 
      - "4242:4242"
    volumes:
      - ./:/code
      - /code/node_modules
    command: sleep infinity