version: '3'

services:
  awsuper-server:
    container_name: awsuper
    image: awsuper
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "4242:4242"
    volumes:
      - ./:/code
      - /code/node_modules
